# Generated by Django 4.2.7 on 2023-12-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='catalog',
            old_name='name',
            new_name='title',
        ),
    ]
