# Generated by Django 4.2.7 on 2023-12-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_review_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.TextField(default='12:00, 12.12.2023'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='reviews'),
        ),
    ]
